### ISSUE TITLE
Blocking YouTube also closes Google login in other domains

### ISSUE THREAD

**Issue by lygamac** [AXeL-dev/distract-me-not#72] opened 2022-09-17 09:24 UTC
Blocking YouTube breaks other google related sites

### Your environment

- 2.8.0
- Firefox 104.0.1

### Steps to reproduce

1. Set block action to `Close tab`
2. add `*.youtube.com` to blacklist
3. Try to log in a Google related product, e.g. [docs.google.com](docs.google.com) (leads to account.google.com)

### Expected behaviour

Log in page should not close like the block action in `Block`

### Actual behaviour

Log in page closes immediately after load

**Comment by lygamac** [comment] 2022-09-17 09:26
Workaround: Add `account.google.com` to the whitelist

**Comment by AXeL-dev** [comment] 2022-09-17 12:38
Hello,

Thanks for your submission, i think that this issue is a duplicate of #25. Please follow the solution proposed here: https://github.com/AXeL-dev/distract-me-not/issues/25#issuecomment-850889954.

You may also need to add the `account.google.com/*` url to your whitelist.

**Closed** 2022-09-17 13:41 UTC
Labels: duplicate
