### ISSUE TITLE
Add option to Schedule Time Window (restrict usage to a 30 minute window for example)

### ISSUE THREAD

**Issue by meximan** [AXeL-dev/distract-me-not#34] opened 2021-08-23 21:25 UTC
Instead of only allowing "schedule blocking time" add another option to Schedule Time Allowed. For example, if I want to limit social media use to 30 minutes per day the scheduled time allowed will allow me to limit it from 3:00 - 3:30 PM.

Thank you!

**Comment by AXeL-dev** [comment] 2021-08-23 22:18
Hello & thanks for your suggestion,

I think this is a duplicate of #19, but let's keep both issues opened for now, since this is a really needed feature, i'll be working on it once i have enough free time to. Nonetheless, any help would be appreciated!

**Comment by AXeL-dev** [comment] 2021-08-28 13:08
![Capture d'écran Deepin_zone de sélection _20210828140710](https://user-images.githubusercontent.com/30635693/131218960-8c023cc5-02be-40b7-b165-0e25b9ba4f30.png)

What do you think about this proposition @meximan ?

**Closed** 2021-08-29 09:46 UTC
Labels: feature request

**Comment by meximan** [comment] 2021-08-29 19:14
Fantastic!

**Comment by meximan** [comment] 2021-09-02 16:29
When will it be implemented?

**Comment by meximan** [comment] 2021-09-02 16:29
What's your donation page?

**Comment by AXeL-dev** [comment] 2021-09-02 17:55
> When will it be implemented?

Already implemented on version **2.5.0** in Firefox & Edge, for chrome the update submission have been refused, i'm checking that with the chrome webstore team.

**Comment by AXeL-dev** [comment] 2021-09-02 17:56
> What's your donation page?

I have a [paypal account](https://www.paypal.me/axeldev) if that works for you.

**Comment by meximan** [comment] 2021-09-06 18:20
Ok sent! Let me know when Chrome accepts the changes!

**Comment by AXeL-dev** [comment] 2021-09-08 17:55
Hey @meximan, the extension has been updated on the [chrome webstore](https://chrome.google.com/webstore/detail/distract-me-not/lkmfokajfoplgdkdifijpffkjeejainc).
