### ISSUE TITLE
Export blacklist

### ISSUE THREAD

**Issue by therealeisbaer** [AXeL-dev/distract-me-not#16] opened 2020-08-24 09:19 UTC
It would be nice if the blacklist could  be exported and imported. If you have to reinitialize your browser, all the marked websites are gone.

**Comment by AXeL-dev** [comment] 2020-08-24 18:25
I think this is a duplicate of #7. will work on this feature once i'll get some time to.

**Closed by AXeL-dev** 2020-08-24 18:25 UTC
